### Criar produto
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "nome": "Laptop",
  "preco": 3200
}

### Listar produtos
GET http://localhost:3000/produtos

### Criar cliente
POST http://localhost:3000/clientes
Content-Type: application/json

{
  "nome": "Laura",
  "sobrenome": "Palmas",
  "telefone": "11999999998",
  "email": "palma@email.com"
}

### Listar clientes
GET http://localhost:3000/clientes

###Listar clientes por id
GET http://localhost:3000/clientes/1

### Criar pedido
POST http://localhost:3000/pedidos
Content-Type: application/json

{
  "produtoId": 3,
  "clienteId": 4,
  "quantidade": 10
}

### Listar pedidos
GET http://localhost:3000/pedidos
